# Test
spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---

spring:
  profiles: local
  datasource:
    driverClassName: org.postgresql.Driver
    username: wonoh
    password: dnjsdh44
    url: jdbc:postgresql://localhost:5432/spa_db
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
